version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: database_lomba
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: rahasia123
      POSTGRES_DB: webdev_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: